name: Deploy Vitepress to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set Git Remote URL
        run: git remote set-url origin https://${{ secrets.TOKEN_PAGE }}@github.com/DiamondStalker/PlayWright.git

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-artifact
          path: docs/.vitepress/dist

      - name: Deploy with gh-pages
        run: npx gh-pages -d docs/.vitepress/dist -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PAGE }}
