name: Deploy Vitepress to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-artifact
          path: docs/.vitepress/dist
      - name: Deploy with gh-pages
        run: |
            git remote set-url origin https://git:${Token_Page}@github.com/${PlayWright}.git
            npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
            GITHUB_TOKEN: ${{ secrets.Token_Page }}
